name: signbridge
description: Effortless Real-Time Sign Language Production

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  avatar_glow: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  http: ^1.1.0
  speech_to_text: ^6.6.0
  translator: ^1.0.0
  google_fonts: 6.1.0
  provider:
  flutter_advanced_switch: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # assets:
  #   - assets/gif/demo.gif
  #   - assets/pose/sample.pose

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700
  #   - family: Trajan Pro

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFE0E7F1"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
