name: New Release

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.13.2"
  APP_NAME: "SignBridge"

jobs:
  build_and_release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Install Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version:[[:space:]]*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/p' pubspec.yaml)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Dependencies
        run: flutter pub get

      - name: Build APK (normal)
        run: flutter build apk

      - name: Upload APK (normal)
        uses: actions/upload-artifact@v3
        with:
          name: apk-result-normal
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build APK (split-per-ABI)
        run: flutter build apk --split-per-abi

      - name: Upload APK (split-per-ABI arm64-v8a)
        uses: actions/upload-artifact@v3
        with:
          name: apk-result-split-per-abi-arm64-v8a
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Upload APK (split-per-ABI armeabi-v7a)
        uses: actions/upload-artifact@v3
        with:
          name: apk-result-split-per-abi-armeabi-v7a
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      - name: Upload APK (split-per-ABI x86_64)
        uses: actions/upload-artifact@v3
        with:
          name: apk-result-split-per-abi-x86_64
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Normal APK Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: ${{ env.APP_NAME }}-${{ steps.get_version.outputs.version }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Split-Per-ABI APKs Release Assets (arm64-v8a)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          asset_name: ${{ env.APP_NAME }}-${{ steps.get_version.outputs.version }}-arm64-v8a.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Split-Per-ABI APKs Release Assets (armeabi-v7a)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          asset_name: ${{ env.APP_NAME }}-${{ steps.get_version.outputs.version }}-armeabi-v7a.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Split-Per-ABI APKs Release Assets (x86_64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-x86_64-release.apk
          asset_name: ${{ env.APP_NAME }}-${{ steps.get_version.outputs.version }}-x86_64.apk
          asset_content_type: application/vnd.android.package-archive
