name: New Release

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.13.2"
  APK_BUILD_DIR: "/tmp/build"

jobs:
  build_apk:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Install Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' pubspec.yaml)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-result
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: [build_apk]
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: apk-result
          path: ${{ github.workspace }}/apk-result

      - name: Copy APK file to root
        run: cp ${{ github.workspace }}/apk-result/*.apk result.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v${{ needs.build_apk.outputs.version }}
          release_name: Release v${{ needs.build_apk.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: result.apk
          asset_name: SignBridge-${{ needs.build_apk.outputs.version }}.apk
          asset_content_type: application/vnd.android.package-archive
